apiVersion: v1
kind: Service
metadata:
  name: backdemo-service-open
spec:
  type: NodePort
  ports:
  - port: 6001 # service 绑定的端口，也就是这个 Service 所对应的 ip 监听的端口
    targetPort: 6000 # targetPort是pod上的端口，从port和nodePort上到来的数据最终经过kube-proxy流入到后端pod的targetPort上进入容器。
    nodePort: 30080
    # 最后可以在minikube容器中 访问svc的clusterip:6001 以及 endpoint:6000 (对内)
  selector:
    app: backdemo
    tier: backend