apiVersion: v1
kind: Service
metadata:
  name: test-stateful-service-mysql
  labels:
    app: testpress
spec:
  ports:
    - port: 3306
  selector:
    app: testpress
    tier: mysql1
  clusterIP: None
