apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefutset-mysql
spec:
  replicas: 3
  serviceName: "test-stateful-service-mysql"
  selector:
    matchLabels:
      app: testpress
      tier: mysql1
  template:
    metadata:
      labels:
        app: testpress
        tier: mysql1
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
        ports:
        - containerPort: 3306
          name: web
        volumeMounts:
        - name: testpress-pv
          mountPath: /var/lib/mysql
#  非持久
  volumeClaimTemplates:
  - metadata:
      name: testpress-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi